org.gradle.jvmargs=-Xmx4g -Dkotlin.daemon.jvm.options=--illegal-access=permit
#kotlin.incremental=false
#kotlin.incremental.jvm=false
kotlin.incremental.useClasspathSnapshot=false
kotlin.stdlib.default.dependency = true

# IDEA
#ideaVersionStart=2022.1
ideaVersionStart=241.19416.15
psiViewerVersion=241-SNAPSHOT


# Project
projectVersion=2025.3.1


# JVM
javaVersion=17