{
	parserClass="com.openc2e.plugins.intellij.agenteering.caos.parser.CaosScriptParser"
	parserUtilClass="com.openc2e.plugins.intellij.agenteering.caos.parser.CaosScriptParserUtil"
	implements="com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
	extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptCompositeElementImpl"
	elementTypeHolderClass="com.openc2e.plugins.intellij.agenteering.caos.lexer.CaosScriptTypes"
	elementTypePrefix="CaosScript_"
	elementTypeClass="com.openc2e.plugins.intellij.agenteering.caos.psi.types.CaosScriptElementType"
	tokenTypeClass="com.openc2e.plugins.intellij.agenteering.caos.lexer.CaosScriptTokenType"
	psiClassPrefix="CaosScript"
	psiImplClassSuffix="Impl"
	psiPackage="com.openc2e.plugins.intellij.agenteering.caos.psi.api"
	psiImplPackage="com.openc2e.plugins.intellij.agenteering.caos.psi.impl"
	elementTypeFactory("command|command_call|command_token|expression|var_token|subroutine|c_targ|constant_assignment|named_var|rvalue|lvalue")="com.openc2e.plugins.intellij.agenteering.caos.psi.types.CaosScriptElementTypeFactory.factory"
	psiImplUtilClass="com.openc2e.plugins.intellij.agenteering.caos.psi.util.CaosScriptPsiImplUtil"
	generateTokenAccessors=true
	generateTokens=true
	name("space.*") = "space or comma"
	tokens = [
		NEWLINE = "regexp:\n";
		K_ENDM = "regexp:[eE][nN][dD][mM]"
		K_SUBR = "regexp:[sS][uU][bB][rR]"
		K_REPS = "regexp:[rR][eE][pP][sS]"
		K_REPE = "regexp:[rR][eE][pP][eE]"
		K_LOOP = "regexp:[lL][oO][oO][pP]"
		K_UNTL = "regexp:[uU][nN][tT][lL]"
		K_EVER = "regexp:[eE][vV][eE][rR]"
		K_ENUM = "regexp:[eE][nN][uU][mM]"
		K_NEXT = "regexp:[nN][eE][xX][tT]"
		K_DOIF = "regexp:[dD][oO][iI][fF]"
		K_ELSE = "regexp:[eE][lL][sS][eE]"
		K_ENDI = "regexp:[eE][nN][dD][iI]"
		K_DOIF = "regexp:[dD][oO][iI][fF]"
		K_SCRP = "regexp:[sS][cC][rR][pP]"
		K_ESCN = "regexp:[eE][sS][cC][nN]"
		K_NSCN = "regexp:[nN][sS][cC][nN]"
		K_ETCH = "regexp:[eE][tT][cC][hH]"
		K_ESEE = "regexp:[eE][sS][eE][eE]"
		VA_XX = "regexp:[Vv][Aa][0-9][0-9]"
		OB_XX = "regexp:[Oo][Vv][0-9][0-9]"
		MV_XX = "regexp:[Mm][Vv][0-9][0-9]"
		VAR_X = "regexp:[Vv][Aa][Rr][0-9]"
		OBV_X = "regexp:[Oo][Bb][Vv][0-9]"
		K_STIM = "regexp:[sS][tT][iI][mM]"
		K_WRIT = "regexp:[wW][rR][iI][tT]"
		K_SHOU = "regexp:[sS][hH][oO][uU]"
		K_SIGN = "regexp:[sS][iI][gG][nN]"
		K_TACT = "regexp:[tT][aA][cC][tT]"
		K_NEW_COL = "regexp:[nN][eE][wW][:]"
		K_BKBD = "regexp:[bB][kK][bB][dD]"
		K_ROOM = "regexp:[rR][oO][oO][mM]"
		K_SIMP = "regexp:[sS][iI][mM][pP]"
		K_PART = "regexp:[pP][aA][rR][tT]"
		K_SPOT = "regexp:[sS][pP][oO][tT]"
		K_CBTN = "regexp:[cC][bB][tT][nN]"
		K_COMP = "regexp:[cC][oO][mM][pP]"
		K_SCEN = "regexp:[sS][cC][eE][nN]"
		K_CABN = "regexp:[cC][aA][bB][nN]"
		K_SCRX = "regexp:[sS][cC][rR][xX]"
		K_SYS_COL = "regexp:[sS][yY][sS][:]"
		K_EDIT = "regexp:[eE][dD][iI][tT]"
		K_TOOL = "regexp:[tT][oO][oO][lL]"
		K_WPOS = "regexp:[wW][pP][oO][sS]"
		K_GENE = "regexp:[gG][eE][nN][eE]"
		K_LIFT = "regexp:[lL][iI][fF][tT]"
		K_VHCL = "regexp:[vV][hH][cC][lL]"
		K_RNDV = "regexp:[rR][nN][dD][vV]"
		K_BBD_COL = "regexp:[bB][bB][dD][:]"
		K_WORD = "regexp:[wW][oO][rR][dD]"
		K_DDE_COL = "regexp:[dD][dD][eE][:]"
		K_CELL = "regexp:[cC][eE][lL][lL]"
		K_FIRE = "regexp:[fF][iI][rR][eE]"
		K_LTCY = "regexp:[lL][tT][cC][yY]"
		K_CREA = "regexp:[cC][rR][eE][aA]"
		K_RTAR = "regexp:[rR][tT][aA][rR]"
		K_TRIG = "regexp:[tT][rR][iI][gG]"
		K_ADDV = "regexp:[aA][dD][dD][vV]"
		K_ANDV = "regexp:[aA][nN][dD][vV]"
		K_DIVV = "regexp:[dD][iI][vV][vV]"
		K_MODV = "regexp:[mM][oO][dD][vV]"
		K_MULV = "regexp:[mM][uU][lL][vV]"
		K_ORRV = "regexp:[oO][rR][rR][vV]"
		K_SETV = "regexp:[sS][eE][tT][vV]"
		K_SUBV = "regexp:[sS][uU][bB][vV]"
		K_BHVR = "regexp:[bB][hH][vV][rR]"
		K_CHEM = "regexp:[cC][hH][eE][mM]"
		K_PUTB = "regexp:[pP][uU][tT][bB]"
		K_KNOB = "regexp:[kK][nN][oO][bB]"
		K_MCRT = "regexp:[mM][cC][rR][tT]"
		K_MESG = "regexp:[mM][eE][sS][gG]"
		K_MVTO = "regexp:[mM][vV][tT][oO]"
		K_SPAS = "regexp:[sS][pP][aA][sS]"
		K_STM_NUM = "regexp:[sS][tT][mM][#]"
		K_CMRA = "regexp:[cC][mM][rR][aA]"
		K_GRND = "regexp:[gG][rR][nN][dD]"
		K_TELE = "regexp:[tT][eE][lL][eE]"
		K_SNDQ = "regexp:[sS][nN][dD][qQ]"
		K_ABRT = "regexp:[aA][bB][rR][tT]"
		K_APPR = "regexp:[aA][pP][pP][rR]"
		K_CMND = "regexp:[cC][mM][nN][dD]"
		K_DIED = "regexp:[dD][iI][eE][dD]"
		K_HATC = "regexp:[hH][aA][tT][cC]"
		K_LIVE = "regexp:[lL][iI][vV][eE]"
		K_LOBE = "regexp:[lL][oO][bB][eE]"
		K_NEGG = "regexp:[nN][eE][gG][gG]"
		K_PANC = "regexp:[pP][aA][nN][cC]"
		K_PICT = "regexp:[pP][iI][cC][tT]"
		K_SCRP = "regexp:[sS][cC][rR][pP]"
		K_DONE = "regexp:[dD][oO][nN][eE]"
		K_DPAS = "regexp:[dD][pP][aA][sS]"
		K_DROP = "regexp:[dD][rR][oO][pP]"
		K_GPAS = "regexp:[gG][pP][aA][sS]"
		K_INST = "regexp:[iI][nN][sS][tT]"
		K_KILL = "regexp:[kK][iI][lL][lL]"
		K_LOCK = "regexp:[lL][oO][cC][kK]"
		K_LOOP = "regexp:[lL][oO][oO][pP]"
		K_MATE = "regexp:[mM][aA][tT][eE]"
		K_MVBY = "regexp:[mM][vV][bB][yY]"
		K_OVER = "regexp:[oO][vV][eE][rR]"
		K_POIN = "regexp:[pP][oO][iI][nN]"
		K_QUIT = "regexp:[qQ][uU][iI][tT]"
		K_SAYN = "regexp:[sS][aA][yY][nN]"
		K_SLIM = "regexp:[sS][lL][iI][mM]"
		K_SLOW = "regexp:[sS][lL][oO][wW]"
		K_SNEZ = "regexp:[sS][nN][eE][zZ]"
		K_STOP = "regexp:[sS][tT][oO][pP]"
		K_STPC = "regexp:[sS][tT][pP][cC]"
		K_CAMT = "regexp:[cC][aA][mM][tT]"
		K_WTOP = "regexp:[wW][tT][oO][pP]"
		K_TOUC = "regexp:[tT][oO][uU][cC]"
		K_UNLK = "regexp:[uU][nN][lL][kK]"
		K_WALK = "regexp:[wW][aA][lL][kK]"
		K_NEGV = "regexp:[nN][eE][gG][vV]"
		K_GSUB = "regexp:[gG][sS][uU][bB]"
		K_PLDS = "regexp:[pP][lL][dD][sS]"
		K_SNDC = "regexp:[sS][nN][dD][cC]"
		K_SNDE = "regexp:[sS][nN][dD][eE]"
		K_SNDF = "regexp:[sS][nN][dD][fF]"
		K_SNDL = "regexp:[sS][nN][dD][lL]"
		K_AIM_COL = "regexp:[aA][iI][mM][:]"
		K_ANIM = "regexp:[aA][nN][iI][mM]"
		K_ASLP = "regexp:[aA][sS][lL][pP]"
		K_BASE = "regexp:[bB][aA][sS][eE]"
		K_EMIT = "regexp:[eE][mM][iI][tT]"
		K_SHOW = "regexp:[sS][hH][oO][wW]"
		K_BDVG = "regexp:[bB][dD][vV][gG]"
		K_DBGM = "regexp:[dD][bB][gG][mM]"
		K_DBUG = "regexp:[dD][bB][uU][gG]"
		K_GETB = "regexp:[gG][eE][tT][bB]"
		K_PUTS = "regexp:[pP][uU][tT][sS]"
		K_PUTV = "regexp:[pP][uU][tT][vV]"
		K_DREA = "regexp:[dD][rR][eE][aA]"
		K_EVNT = "regexp:[eE][vV][nN][tT]"
		K_IMPT = "regexp:[iI][mM][pP][tT]"
		K_POSE = "regexp:[pP][oO][sS][eE]"
		K_PRLD = "regexp:[pP][rR][lL][dD]"
		K_RMEV = "regexp:[rR][mM][eE][vV]"
		K_SAY_DOL = "regexp:[sS][aA][yY][$]"
		K_SNDV = "regexp:[sS][nN][dD][vV]"
		K_TARG = "regexp:[tT][aA][rR][gG]"
		K_TICK = "regexp:[tT][iI][cC][kK]"
		K_VRSN = "regexp:[vV][rR][sS][nN]"
		K_WAIT = "regexp:[wW][aA][iI][tT]"
		K_WRLD = "regexp:[wW][rR][lL][dD]"
		K_TOTL = "regexp:[tT][oO][tT][lL]"
		K__IT_ = "regexp:[_][iI][tT][_]"
		K_ACTV = "regexp:[aA][cC][tT][vV]"
		K_ATTN = "regexp:[aA][tT][tT][nN]"
		K_ATTR = "regexp:[aA][tT][tT][rR]"
		K_BABY = "regexp:[bB][aA][bB][yY]"
		K_BUMP = "regexp:[bB][uU][mM][pP]"
		K_CAGE = "regexp:[cC][aA][gG][eE]"
		K_CAMN = "regexp:[cC][aA][mM][nN]"
		K_CARR = "regexp:[cC][aA][rR][rR]"
		K_CLAS = "regexp:[cC][lL][aA][sS]"
		K_DEAD = "regexp:[dD][eE][aA][dD]"
		K_DRV_EXL = "regexp:[dD][rR][vV][!]"
		K_EXEC = "regexp:[eE][xX][eE][cC]"
		K_FMLY = "regexp:[fF][mM][lL][yY]"
		K_FROM = "regexp:[fF][rR][oO][mM]"
		K_GND_NUM = "regexp:[gG][nN][dD][#]"
		K_GNDW = "regexp:[gG][nN][dD][wW]"
		K_GNUS = "regexp:[gG][nN][uU][sS]"
		K_HGHT = "regexp:[hH][gG][hH][tT]"
		K_HOUR = "regexp:[hH][oO][uU][rR]"
		K_LIMB = "regexp:[lL][iI][mM][bB]"
		K_LIML = "regexp:[lL][iI][mM][lL]"
		K_LIMR = "regexp:[lL][iI][mM][rR]"
		K_LIMT = "regexp:[lL][iI][mM][tT]"
		K_MINS = "regexp:[mM][iI][nN][sS]"
		K_MOVS = "regexp:[mM][oO][vV][sS]"
		K_NEID = "regexp:[nN][eE][iI][dD]"
		K_NORN = "regexp:[nN][oO][rR][nN]"
		K_OBJP = "regexp:[oO][bB][jJ][pP]"
		K_OWNR = "regexp:[oO][wW][nN][rR]"
		K_PNTR = "regexp:[pP][nN][tT][rR]"
		K_POSB = "regexp:[pP][oO][sS][bB]"
		K_POSL = "regexp:[pP][oO][sS][lL]"
		K_POSR = "regexp:[pP][oO][sS][rR]"
		K_POST = "regexp:[pP][oO][sS][tT]"
		K_RMS_NUM = "regexp:[rR][mM][sS][#]"
		K_SCOR = "regexp:[sS][cC][oO][rR]"
		K_SNDS = "regexp:[sS][nN][dD][sS]"
		K_SPCS = "regexp:[sS][pP][cC][sS]"
		K_TCAR = "regexp:[tT][cC][aA][rR]"
		K_TEMP = "regexp:[tT][eE][mM][pP]"
		K_WDTH = "regexp:[wW][dD][tT][hH]"
		K_WIND = "regexp:[wW][iI][nN][dD]"
		K_WINH = "regexp:[wW][iI][nN][hH]"
		K_WINW = "regexp:[wW][iI][nN][wW]"
		K_XVEC = "regexp:[xX][vV][eE][cC]"
		K_YVEC = "regexp:[yY][vV][eE][cC]"
		K_DRIV = "regexp:[dD][rR][iI][vV]"
		K_TOKN = "regexp:[tT][oO][kK][nN]"
		K_CONST = "regexp:[*]\s*[Cc][Oo][nN][sS][tT]";
		EQ_SPACE = "regexp:\s*=\s*";
		N_CONST = "regexp:[:][a-zA-Z_0-9]+"
		N_VAR = "regexp:[$][a-zA-Z_0-9]+"
		COMMENT_LITERAL = "regexp:\*[^\n]*"
		DECIMAL = "regexp:[0-9]+\.[0-9]+"
		INT = "regexp:[0-9]+"
		TEXT_LITERAL = 'regexp:\[[^]]*]';
		QUOTE_STRING = 'regexp:"[^\n|"]*"'
		ID = "regexp:[_a-zA-Z][_a-zA-Z0-9!#]*";
		COLON = ':';
		PLUS = "+";
		SPACE_ = "regexp:[ ]";
		space = "regexp:\n[\t ]+";
		OPEN_BRACKET = '[';
		CLOSE_BRACKET = ']';
		COMMA = ',';
		ANIM_R = "R"


	]
}

def	::= (constant_assignment NEWLINE)* (script_body_element (!<<eof>> space_like_or_newline script_body_element)*  space_like?)? c_endm?
	;

script_body_element
	::= event_script
	|	macro
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
			getBlockType
		]
	}
	;

macro
	::= macro_code_block space_like_or_newline script_terminator?
	{

		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptMacroStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
			getBlockType
		]
	}
	;

private macro_code_block
	::= code_block
	{
		recoverWhile = macro_code_block_recover
	}
	;

private macro_code_block_recover
	::= !(K_ENDM|c_endm|<<eofNext>>)
	;

code_block
	::= code_block_line (space_like_or_newline code_block_line)*
	{
		pin=1
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
	}
	;

code_block_line
	::= caos_element
	;

private caos_element
	::=	control_statement
	|	command_call
	|	expression_list
	;


event_script
	::= c_scrp space_like classifier space_like event_number space_like_or_newline (<<enterMode "eventScript">>event_script_body space_like_or_newline)? <<exitMode "eventScript">>script_terminator
	{
		pin=1
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptScrpStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
			getBlockType
		]
	}
	;

c_scrp ::= K_SCRP
{
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		getReference
		getCommandString
		isVariant
		getName
		setName
	]
}
;


private event_script_body
	::= code_block
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
		]
		recoverWhile=event_script_body_recover
	}
	;

private event_script_body_recover
	::= !(K_ENDM|<<eofNext>>)
	;

subroutine
	::= c_subr space_like subroutine_name space_like_or_newline (subroutine_body space_like_or_newline)? cc_retn
	{
		pin=1
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptSubroutineStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
		]
		methods = [
			getBlockType
		]
	}
	;

c_subr
	::= K_SUBR
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

cc_retn
	::= K_RETN
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

private subroutine_body
	::= code_block
	{
		recoverWhile=subroutine_body_recover
	}
	;

private subroutine_body_recover
	::= !(!<<insideBlock>> (K_RETN|c_retn)|K_ENDM|<<eofNext>>)
	;

classifier
	::= family space_like genus space_like species
	;

private control_statement
   ::=  subroutine
   |	loop_statement
   |   	repeat_statement
   |   	enum_next_statement
   |   	enum_scenery_statement
   |	doif_statement
   ;

expression_list
	::= expression (!new_line_like space_like expression)* space_like?
	{
		pin(".*")=1
		recoverWhile=expression_list_recover
	}

private expression_list_recover
	::= !(NEWLINE|',')
	;

loop_statement
   ::= c_loop space_like_or_newline <<enterBlock>>loop_body? space_like_or_newline loop_terminator<<exitBlock>>
	{
		pin=1
		implements = [
			 "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			 "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
			 "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptNoJump"
		]
		methods = [
			isEver
			isUntil
			getBlockType
		]
	}
	;

loop_terminator
	::= cEver
	|	untl_terminator
	{
		pin=1
	}
	;



private untl_terminator
	::= c_untl space_like equality_expression
	{
		pin=1
	}
	;



private loop_body
	::= code_block
	{
		recoverWhile=loop_body_recover
	}
	;

private loop_body_recover
	::= !(K_EVER|K_UNTL|<<eofNext>>)
	;

repeat_statement
	::= c_reps space_like rvalue space_like_or_newline <<enterBlock>>(repeat_body space_like_or_newline)? c_repe<<exitBlock>>
	{
		pin=1
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptNoJump"
		]

		methods = [
			getBlockType
		]

	}
	;


private repeat_body
   ::= code_block
   {
      recoverWhile=repeat_body_recover
   }
   ;

private repeat_body_recover
	::= !(K_REPE|c_repe|<<eofNext>>)
	;


enum_next_statement
	::= c_enum space_like classifier space_like_or_newline <<enterBlock>>(enum_body space_like_or_newline)? c_next<<exitBlock>>
	{
		pin=1;
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptNoJump"
		]
		methods = [
			codeBlock="code_block"
			getBlockType
		]
	}
	;


enum_scenery_statement
   ::= c_escn space_like classifier space_like_or_newline <<enterBlock>>(escn_body space_like_or_newline)? c_nscn<<exitBlock>>
   {
		pin=1;
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptNoJump"
		]
		methods = [
			getBlockType
		]
   }
   ;


private enum_body
   ::= code_block
   {
      implements = [
         "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
         "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
      ]
      recoverWhile=enum_body_recover
   }
   ;

private enum_body_recover
	::= !(K_NEXT)
	;

private escn_body
   ::= code_block
   {
      recoverWhile=escn_body_recover
   }
   ;

private escn_body_recover
	::= !(K_NSCN)
	;

doif_statement
	::= doif_statement_statement (else_if_statement space_like_or_newline)* (else_statement space_like_or_newline)? c_endi<<exitBlock>>
	{
		pin=1
		implements = [
			 "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
	}
	;

doif_statement_statement
	::= c_doif space_like equality_expression space_like_or_newline <<enterBlock>>(do_if_body space_like_or_newline)?
	{
		pin=1
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
		]
		methods = [
			getBlockType
		]
	}
	;


else_if_statement
	::= c_elif space_like equality_expression space_like_or_newline do_if_body?
	{
		pin=1
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
		]
		methods = [
			getBlockType
		]
	}
	;

else_statement
	::= c_else space_like_or_newline else_block
	{
		pin=1;
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptHasCodeBlock"
		]
		methods = [
			getBlockType
		]
	}
	;


private else_block
	::= code_block
	{
		recoverWhile=else_body_recover
	}
	;

private else_body_recover
	::= !(K_ELSE|K_ELIF|K_ENDI)
	;

private do_if_body
	::= code_block
	{
		recoverWhile=do_if_body_recover
	}
	;

private do_if_body_recover
	::= !(K_ELSE|K_ELIF|K_ENDI)
	;
c_loop
	::= K_LOOP
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

cEver
	::= K_EVER
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;
c_untl
	::= K_UNTL
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;
c_reps ::= K_REPS
{
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		getReference
		getCommandString
		isVariant
		getName
		setName
	]
}
;
c_repe ::= K_REPE
{
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		getReference
		getCommandString
		isVariant
		getName
		setName
	]
}
;
c_enum
	::= K_ENUM
	|	K_ESEE
	| 	K_ETCH
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;
c_next ::= K_NEXT
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;
c_escn ::= K_ESCN
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

c_nscn ::= K_NSCN
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

c_doif::=K_DOIF
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

c_endi ::= K_ENDI
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

c_elif ::= K_ELIF
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;
c_else ::= K_ELSE
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;
command_call
	::= c_commands_rrrrrrrrrrrrr
	|   c_commands_rrrrrrrrrrrr
	|   c_commands_trrrrr
	|   c_commands_rrrrrr
	|   c_commands_trrrr
	|   c_commands_rrrrr
	|   c_commands_trrr
	|   c_commands_rrrr
	|   c_commands_rrl
	|   c_commands_trr
	|   c_commands_lrr
	|   c_commands_rrr
	|   c_assignment
	|   c_commands_rr
	|   c_commands_tr
	|   c_commands_no_args
	|   c_commands_l
	|   c_commands_t
	|	c_gsub
	|	c_targ
	|   c_commands_r
	{
		pin=2
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptCommandCallStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getCommandString
			getCommandTokens
			getParameterTypes
			getParametersLength
			getCommandTokens
			getCommand
		]
	//recoverWhile = command_recover
	}
	;


c_commands_rrrrrrrrrrrrr ::= c_kw_rrrrrrrrrrrrr space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrrrrrrrrrrrr"
		getCommandString
	]
}
;

c_commands_rrrrrrrrrrrr ::= c_kw_rrrrrrrrrrrr space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrrrrrrrrrrr"
		getCommandString
	]
}
;

c_commands_trrrrr ::= c_kw_trrrrr space_like token space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_trrrrr"
		getCommandString
	]
}
;

c_commands_rrrrrr ::= c_kw_rrrrrr space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrrrrr"
		getCommandString
	]
}
;

c_commands_trrrr ::= c_kw_trrrr space_like token space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_trrrr"
		getCommandString
	]
}
;

c_commands_rrrrr ::= c_kw_rrrrr space_like rvalue space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrrrr"
		getCommandString
	]
}
;

c_commands_trrr ::= c_kw_trrr space_like token space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_trrr"
		getCommandString
	]
}
;

c_commands_rrrr ::= c_kw_rrrr space_like rvalue space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrrr"
		getCommandString
	]
}
;

c_commands_rrl ::= c_kw_rrl space_like rvalue space_like rvalue space_like lvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrl"
		getCommandString
	]
}
;

c_commands_trr ::= c_kw_trr space_like token space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_trr"
		getCommandString
	]
}
;

c_commands_lrr ::= c_kw_lrr space_like lvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_lrr"
		getCommandString
	]
}
;

c_commands_rrr ::= c_kw_rrr space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rrr"
		getCommandString
	]
}
;

c_assignment ::= c_kw_assignment space_like lvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptAssignmentStub"
	extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
	methods = [
		commandToken="/c_kw_assignment"
		getRvalueString
		getLvalueString
		getCommandString
	]
}
;

c_commands_rr ::= c_kw_rr space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_rr"
		getCommandString
	]
}
;

c_commands_tr ::= c_kw_tr space_like token space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_tr"
		getCommandString
	]
}
;

c_commands_no_args ::= c_kw_no_args
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_no_args"
		getCommandString
	]
}
;

c_commands_l ::= c_kw_l space_like lvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_l"
		getCommandString
	]
}
;

c_commands_t ::= c_kw_t space_like token
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_t"
		getCommandString
	]
}
;

c_targ
	::= K_TARG space_like rvalue
	{
		pin=1
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptTargStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		methods = [
			getTargetString
		]
	}
	;

c_commands_r ::= c_kw_r space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/c_kw_r"
		getCommandString
	]
}
;

private rvalue_prime
	::= r_rvalue_rrr
	|	r_rvalue_rr
	|	r_rvalue_r
	|	r_rvalue_t
	|	r_rvalue_no_args
	| 	var_token
	|	named_var
	|	named_constant
	;


rvalue
	::= rvalue_prime
	|	named_constant
	|	named_var
	|	expression
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptArgument"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			getCommandToken
     		getCommandString
     		getIndex
     		toCaosVar
		]
	}
	;

r_rvalue_rrr ::= r_kw_rrr space_like rvalue space_like rvalue space_like rvalue
{
	pin=1
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/r_kw_rrr"
		getCommandString
	]
}
;

r_rvalue_no_args ::= r_kw_no_args
{
	pin=1
	implements = [
	  "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/r_kw_no_args"
		getCommandString
	]
}
;

r_rvalue_rr ::= r_kw_rr space_like rvalue space_like rvalue
{
	pin=1
	implements = [
	  "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		commandToken="/r_kw_rr"
		getCommandString
	]
}
;

r_rvalue_r ::= r_kw_r space_like rvalue
{
   pin=1
   implements = [
      "com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   ]
   methods = [
		commandToken="/r_kw_r"
		getCommandString
   ]
}
;

r_rvalue_t ::= r_kw_t space_like token
{
   pin=1
   implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   ]
   methods = [
		commandToken="/r_kw_t"
		getCommandString
   ]
}

lvalue
	::=	l_kw_no_args
	| 	var_token
	|	named_var
	{
		pin=1
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptArgument"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
		]
		methods = [
			commandToken="/l_kw_no_args"
			getCommandString
			isVariant
			getIndex
			getCommandToken
		]
	}
	;

c_kw_rrrrrrrrrrrrr
   ::= K_STIM space_like K_WRIT
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   		]
   		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_rrrrrrrrrrrr
   ::= K_STIM space_like K_SHOU
   |   K_STIM space_like K_SIGN
   |   K_STIM space_like K_TACT
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_trrrrr
   ::= K_NEW_COL space_like K_BKBD
	{
		pin = 3;
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
   ;

c_kw_rrrrrr
   ::= K_ROOM
   {
   		pin = 1;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
			isVariant
			getName
			setName
			getCommandString
   		]
   }
   ;

c_kw_trrrr
   ::= K_NEW_COL space_like K_SIMP
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_rrrrr
   ::= K_NEW_COL space_like K_PART
   |   K_SPOT
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_trrr
   ::= K_NEW_COL space_like K_CBTN
   |   K_NEW_COL space_like K_COMP
   |   K_NEW_COL space_like K_SCEN
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_rrrr
   ::= K_CABN
   |   K_SCRX
   |   K_SYS_COL space_like K_EDIT
   |   K_TOOL
   |   K_WPOS
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_rrl
   ::= K_NEW_COL space_like K_GENE
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_trr
   ::= K_NEW_COL space_like K_LIFT
   |   K_NEW_COL space_like K_VHCL
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_lrr
   ::= K_RNDV
   {
   		pin = 1;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_rrr
   ::= K_BBD_COL space_like K_WORD
   |   K_DDE_COL space_like K_CELL
   |   K_FIRE
   |   K_LTCY
   |   K_NEW_COL space_like K_CREA
   |   K_RTAR
   |   K_TRIG
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_assignment
   ::= K_ADDV
   |   K_ANDV
   |   K_DIVV
   |   K_MODV
   |   K_MULV
   |   K_ORRV
   |   K_SETV
   |   K_SUBV
   {
   		pin = 1;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_rr
   ::= K_BHVR
   |   K_CHEM
   |   K_DDE_COL space_like K_PUTB
   |   K_KNOB
   |   K_MCRT
   |   K_MESG space_like K_WRIT
   |   K_MVTO
   |   K_SPAS
   |   K_STM_NUM space_like K_WRIT
   |   K_SYS_COL space_like K_CMRA
   |   K_SYS_COL space_like K_GRND
   |   K_TELE
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_tr
   ::= K_SNDQ
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_no_args
	::= K_ABRT
	|   K_APPR
	|   K_CMND
	|   K_DDE_COL space_like K_DIED
	|   K_DDE_COL space_like K_GENE
	|   K_DDE_COL space_like K_HATC
	|   K_DDE_COL space_like K_LIVE
	|   K_DDE_COL space_like K_LOBE
	|   K_DDE_COL space_like K_NEGG
	|   K_DDE_COL space_like K_PANC
	|   K_DDE_COL space_like K_PICT
	|   K_DDE_COL space_like K_SCRP
	|   K_DONE
	|   K_DPAS
	|   K_DROP
	|   K_EDIT
	|   K_GPAS
	|   K_INST
	|   K_LOCK
	|   K_MATE
	|   K_MVBY
	|   K_OVER
	|   K_PART
	|   K_POIN
	|   K_QUIT
	|   K_SAYN
	|   K_SLIM
	|   K_SLOW
	|   K_SNEZ
	|   K_STOP
	|   K_STPC
	|   K_SYS_COL space_like K_CAMT
	|   K_SYS_COL space_like K_WTOP
	|   K_UNLK
	|   K_WALK
	|	c_iscr
	|	<<insideBlock>> c_retn
   {
   		pin = 3;
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_iscr ::= K_ISCR
{
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		getReference
		getCommandString
		isVariant
		getName
		setName
	]
}
;
c_retn
	::= K_RETN
	{
		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
   			getCommandString
			isVariant
			getName
			setName
			getReference
		]
	}
	;

c_kw_l
   ::= K_NEGV
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;
c_gsub
	::= K_GSUB space_like subroutine_name
	{
		pin=1
	}
	;
c_kw_t
   ::= K_PLDS
   |   K_SNDC
   |   K_SNDE
   |   K_SNDF
   |   K_SNDL
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

c_kw_r
	::= K_AIM_COL
	|   K_ANIM
	|   K_ASLP
	|   K_BASE
	|   K_BBD_COL spacce K_EDIT
	|   K_BBD_COL space_like K_EMIT
	|   K_BBD_COL space_like K_SHOW
	|   K_BDVG
	|   K_DBGM
	|   K_DBUG
	|   K_DDE_COL space_like K_GETB
	|   K_DDE_COL space_like K_PUTS
	|   K_DDE_COL space_like K_PUTV
	|   K_DDE_COL space_like K_WORD
	|   K_DREA
	|   K_EVNT
	|   K_IMPT
	|   K_MESG space_like K_SHOU
	|   K_MESG space_like K_TACT
	|   K_POSE
	|   K_PRLD
	|   K_RMEV
	|   K_SAY_DOL
	|   K_SNDV
	|   K_STM_NUM space_like K_SHOU
	|   K_STM_NUM space_like K_TACT
	|   K_TICK
	|   K_VRSN
	|   K_WAIT
	|   K_WRLD
	|   K_KILL
	{
		pin = 3;
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandKeywordToken"
		]
		methods = [
			getReference
			getCommandString
			isVariant
			getName
			setName
		]
	}
	;


r_kw_rrr
   ::= K_TOTL
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsRvalueKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

r_kw_no_args
   ::= K_OBVX
   |   K_VARX
   |   K__IT_
   |   K_ACTV
   |   K_ASLP
   |   K_ATTN
   |   K_ATTR
   |   K_BABY
   |   K_BUMP
   |   K_CAGE
   |   K_CAMN
   |   K_CARR
   |   K_CLAS
   |   K_DEAD
   |   K_DRV_EXL
   |   K_EDIT
   |   K_EXEC
   |   K_FMLY
   |   K_FROM
   |   K_GND_NUM
   |   K_GNDW
   |   K_GNUS
   |   K_HGHT
   |   K_HOUR
   |   K_LIMB
   |   K_LIML
   |   K_LIMR
   |   K_LIMT
   |   K_MINS
   |   K_MOVS
   |   K_NEID
   |   K_NORN
   |   K_OBJP
   |   K_OWNR
   |   K_PNTR
   |   K_POSB
   |   K_POSE
   |   K_POSL
   |   K_POSR
   |   K_POST
   |   K_RMS_NUM
   |   K_SCOR
   |   K_SNDS
   |   K_SPCS
   |   K_TARG
   |   K_TCAR
   |   K_TEMP
   |   K_VRSN
   |   K_WDTH
   |   K_WIND
   |   K_WINH
   |   K_WINW
   |   K_XVEC
   |   K_YVEC
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsRvalueKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

r_kw_rr
   ::= K_ROOM
   |   K_TOUC
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsRvalueKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

r_kw_r
   ::= K_CHEM
   |   K_DRIV
   |   K_GRND
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsRvalueKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

r_kw_t
   ::= K_TOKN
   {
   		implements = [
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsRvalueKeywordToken"
   		]
   		methods = [
   			getReference
   			getCommandString
			isVariant
			getName
			setName
   		]
   }
   ;

l_kw_no_args
	::= K_OBVX
	|   K_VARX
	|   K_ACTV
	|   K_ATTR
	|   K_BABY
	|   K_NORN
	|   K_OBJP
	|   K_WINH
	|   K_WINW
	|   K_XVEC
	|	K_YVEC
	|   K_CLAS
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
   			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsLvalueKeywordToken"
		]
		methods = [
			getReference
   			getCommandString
			isVariant
			getName
			setName
		]
	}
	;

animation_string
   ::= '[' INT ANIM_R? ']'
   ;

byte_string
	::= '[' INT (space_like INT)* ']'
	;

new_line_like
	::= symbol_comma
	|	NEWLINE
	|	<<eof>>
	;

symbol_comma
	::= COMMA
	;

space_like_or_newline
	::= (space_like new_line_like?) (new_line_like|space_like)*
	|	(new_line_like space_like?) (new_line_like|space_like)*
	;
space_like
	::= space+
	;

private space
	::= SPACE_
	;

private expression
   ::= 	/*equality_expression
   |   	*/animation_string
   |	byte_string
   |   	expression_prime
   {
   		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptExpressionStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
			getType
		]
   }
   ;


private expression_prime
   ::= //command_call
   		rvalue_prime
   |	literal
   |	var_token
   ;

equality_expression
   ::= expression_prime space_like eq_op space_like expression_prime
   {
   		pin=3
   }
   ;

eq_op
	::= eq_op_old
	|	eq_op_new
	;

eq_op_old
	::= EQ_OP_OLD_
	;

eq_op_new
	::= EQ_OP_NEW_
	;

var_token
	::= VA_XX
	| 	OV_XX
	|	OBV_X
	|	VAR_X
	|	MV_XX
	{
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptVarTokenStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
			getVarGroup
			getVarIndex
		]
	}
	;

literal
   ::= string_literal
   |   number
   {
      methods = [
         intValue
         isInt
         floatValue
         isFloat
         isNumeric
         stringValue
         isString
      ]
   }
   ;

number
	::= INT
	|	DECIMAL
   ;

string_literal
   ::= QUOTE_STRING
   |   '[' TEXT_LITERAL? ']'
   {
      methods = [
         getStringValue
      ]
   }
   ;

subroutine_name
	::= K_STIM
	|   K_WRIT
	|   K_SHOU
	|   K_SIGN
	|   K_TACT
	|   K_NEW_COL
	|   K_BKBD
	|   K_ROOM
	|   K_SIMP
	|   K_PART
	|   K_SPOT
	|   K_CBTN
	|   K_COMP
	|   K_SCEN
	|   K_CABN
	|   K_SCRX
	|   K_SYS_COL
	|   K_EDIT
	|   K_TOOL
	|   K_WPOS
	|   K_GENE
	|   K_LIFT
	|   K_VHCL
	|   K_RNDV
	|   K_BBD_COL
	|   K_WORD
	|   K_DDE_COL
	|   K_CELL
	|  	K_DOIF
	|   K_ENUM
	|   K_FIRE
	|   K_LTCY
	|   K_CREA
	|   K_RTAR
	|   K_TRIG
	|   K_UNTL
	|   K_ADDV
	|   K_ANDV
	|   K_DIVV
	|   K_MODV
	|   K_MULV
	|   K_ORRV
	|   K_SETV
	|   K_SUBV
	|   K_BHVR
	|   K_CHEM
	|   K_PUTB
	|   K_KNOB
	|   K_MCRT
	|   K_MESG
	|   K_MVTO
	|   K_SPAS
	|   K_STM_NUM
	|   K_CMRA
	|   K_GRND
	|   K_TELE
	|   K_SNDQ
	|   K_ABRT
	|   K_APPR
	|   K_CMND
	|   K_DIED
	|   K_HATC
	|   K_LIVE
	|   K_LOBE
	|   K_NEGG
	|   K_PANC
	|   K_PICT
	|   K_SCRP
	|   K_DONE
	|   K_DPAS
	|   K_DROP
	|   K_ELSE
	|   K_ENDI
	|   K_ENDM
	|   K_GPAS
	|   K_INST
	|   K_KILL
	|   K_LOCK
	|   K_LOOP
	|   K_MATE
	|   K_MVBY
	|   K_NEXT
	|   K_OVER
	|   K_POIN
	|   K_QUIT
	|   K_REPE
	|   K_RETN
	|   K_SAYN
	|   K_SLIM
	|   K_SLOW
	|   K_SNEZ
	|   K_STOP
	|   K_STPC
	|   K_CAMT
	|   K_WTOP
	|   K_TOUC
	|   K_UNLK
	|   K_WALK
	|   K_NEGV
	|   K_GSUB
	|   K_PLDS
	|   K_SNDC
	|   K_SNDE
	|   K_SNDF
	|   K_SNDL
	|   K_SUBR
	|   K_AIM_COL
	|   K_ANIM
	|   K_ASLP
	|   K_BASE
	|   K_EMIT
	|   K_SHOW
	|   K_BDVG
	|   K_DBGM
	|   K_DBUG
	|   K_GETB
	|   K_PUTS
	|   K_PUTV
	|   K_DREA
	|   K_EVNT
	|   K_IMPT
	|   K_POSE
	|   K_PRLD
	|   K_REPS
	|   K_RMEV
	|   K_SAY_DOL
	|   K_SNDV
	|   K_TARG
	|   K_TICK
	|   K_VRSN
	|   K_WAIT
	|   K_WRLD
	|   K_TOTL
	|   OBVX
	|   VARX
	|   K__IT_
	|   K_ACTV
	|   K_ATTN
	|   K_ATTR
	|   K_BABY
	|   K_BUMP
	|   K_CAGE
	|   K_CAMN
	|   K_CARR
	|   K_CLAS
	|   K_DEAD
	|   K_DRV_EXL
	|   K_EXEC
	|   K_FMLY
	|   K_FROM
	|   K_GND_NUM
	|   K_GNDW
	|   K_GNUS
	|   K_HGHT
	|   K_HOUR
	|   K_LIMB
	|   K_LIML
	|   K_LIMR
	|   K_LIMT
	|   K_MINS
	|   K_MOVS
	|   K_NEID
	|   K_NORN
	|   K_OBJP
	|   K_OWNR
	|   K_PNTR
	|   K_POSB
	|   K_POSL
	|   K_POSR
	|   K_POST
	|   K_RMS_NUM
	|   K_SCOR
	|   K_SNDS
	|   K_SPCS
	|   K_TCAR
	|   K_TEMP
	|   K_WDTH
	|   K_WIND
	|   K_WINH
	|   K_WINW
	|   K_XVEC
	|   K_YVEC
	|   K_DRIV
	|   K_TOKN
	|	K_ELIF
	|	K_NSCN
	|	K_ESCN
	|	K_ESEE
	| 	K_ETCH
	|	WORD
	{
		implements = [
			"com.intellij.psi.PsiNamedElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		]
		methods = [
			getName
			setName
			getReference
		]
	};

token
	::= K_STIM
	|	K_ESEE
	| 	K_ETCH
	|   K_WRIT
	|   K_SHOU
	|   K_SIGN
	|   K_TACT
	|   K_NEW_COL
	|   K_BKBD
	|   K_ROOM
	|   K_SIMP
	|   K_PART
	|   K_SPOT
	|   K_CBTN
	|   K_COMP
	|   K_SCEN
	|   K_CABN
	|   K_SCRX
	|   K_SYS_COL
	|   K_EDIT
	|   K_TOOL
	|   K_WPOS
	|   K_GENE
	|   K_LIFT
	|   K_VHCL
	|   K_RNDV
	|   K_BBD_COL
	|   K_WORD
	|   K_DDE_COL
	|   K_CELL
	|  	K_DOIF
	|   K_ENUM
	|   K_FIRE
	|   K_LTCY
	|   K_CREA
	|   K_RTAR
	|   K_TRIG
	|   K_UNTL
	|   K_ADDV
	|   K_ANDV
	|   K_DIVV
	|   K_MODV
	|   K_MULV
	|   K_ORRV
	|   K_SETV
	|   K_SUBV
	|   K_BHVR
	|   K_CHEM
	|   K_PUTB
	|   K_KNOB
	|   K_MCRT
	|   K_MESG
	|   K_MVTO
	|   K_SPAS
	|   K_STM_NUM
	|   K_CMRA
	|   K_GRND
	|   K_TELE
	|   K_SNDQ
	|   K_ABRT
	|   K_APPR
	|   K_CMND
	|   K_DIED
	|   K_HATC
	|   K_LIVE
	|   K_LOBE
	|   K_NEGG
	|   K_PANC
	|   K_PICT
	|   K_SCRP
	|   K_DONE
	|   K_DPAS
	|   K_DROP
	|   K_ELSE
	|   K_ENDI
	|   K_ENDM
	|   K_GPAS
	|   K_INST
	|   K_KILL
	|   K_LOCK
	|   K_LOOP
	|   K_MATE
	|   K_MVBY
	|   K_NEXT
	|   K_OVER
	|   K_POIN
	|   K_QUIT
	|   K_REPE
	|   K_RETN
	|   K_SAYN
	|   K_SLIM
	|   K_SLOW
	|   K_SNEZ
	|   K_STOP
	|   K_STPC
	|   K_CAMT
	|   K_WTOP
	|   K_TOUC
	|   K_UNLK
	|   K_WALK
	|   K_NEGV
	|   K_GSUB
	|   K_PLDS
	|   K_SNDC
	|   K_SNDE
	|   K_SNDF
	|   K_SNDL
	|   K_SUBR
	|   K_AIM_COL
	|   K_ANIM
	|   K_ASLP
	|   K_BASE
	|   K_EMIT
	|   K_SHOW
	|   K_BDVG
	|   K_DBGM
	|   K_DBUG
	|   K_GETB
	|   K_PUTS
	|   K_PUTV
	|   K_DREA
	|   K_EVNT
	|   K_IMPT
	|   K_POSE
	|   K_PRLD
	|   K_REPS
	|   K_RMEV
	|   K_SAY_DOL
	|   K_SNDV
	|   K_TARG
	|   K_TICK
	|   K_VRSN
	|   K_WAIT
	|   K_WRLD
	|   K_TOTL
	|   OBVX
	|   VARX
	|   K__IT_
	|   K_ACTV
	|   K_ATTN
	|   K_ATTR
	|   K_BABY
	|   K_BUMP
	|   K_CAGE
	|   K_CAMN
	|   K_CARR
	|   K_CLAS
	|   K_DEAD
	|   K_DRV_EXL
	|   K_EXEC
	|   K_FMLY
	|   K_FROM
	|   K_GND_NUM
	|   K_GNDW
	|   K_GNUS
	|   K_HGHT
	|   K_HOUR
	|   K_LIMB
	|   K_LIML
	|   K_LIMR
	|   K_LIMT
	|   K_MINS
	|   K_MOVS
	|   K_NEID
	|   K_NORN
	|   K_OBJP
	|   K_OWNR
	|   K_PNTR
	|   K_POSB
	|   K_POSL
	|   K_POSR
	|   K_POST
	|   K_RMS_NUM
	|   K_SCOR
	|   K_SNDS
	|   K_SPCS
	|   K_TCAR
	|   K_TEMP
	|   K_WDTH
	|   K_WIND
	|   K_WINH
	|   K_WINW
	|   K_XVEC
	|   K_YVEC
	|   K_DRIV
	|   K_TOKN
	|	K_ELIF
	|	K_NSCN
	|	K_ESCN
	|	WORD
	{
		implements = [
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
			"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
		]
		methods = [
			isVariant
			getReference
			getName
			setName
		]
	}
	;
script_terminator
	::= c_endm
	|   <<eos>>
	|	<<eof>>
	;

c_endm ::= K_ENDM
{
	implements = [
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptIsCommandToken"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCompositeElement"
		"com.openc2e.plugins.intellij.agenteering.caos.psi.api.CaosScriptCommandLike"
	]
	methods = [
		getReference
		getCommandString
		isVariant
		getName
		setName
	]
}
;

constant_assignment
	::= K_CONST ID EQ_SPACE INT
	{
		pin=1
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptConstantAssignmentStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		methods = [
			getNumberValue
			name="/ID"
			value="/INT"
		]
	}
	;

named_constant
	::= N_CONST
	;

named_var
	::= N_VAR
	{
		stubClass="com.openc2e.plugins.intellij.agenteering.caos.stubs.api.CaosScriptNamedVarStub"
		extends="com.openc2e.plugins.intellij.agenteering.caos.psi.impl.CaosScriptStubBasedElementImpl<?>"
		methods = [
			getScope
			getVarName
			getAction
		]
	}
	;


family ::= INT | rvalue;
genus ::= INT | rvalue;
species ::= INT | rvalue;

event_number
	::= INT
	;

